#! /bin/sh

PERCENT=$(cat /sys/class/power_supply/BAT0/capacity)
CHARGING=$(cat /sys/class/power_supply/BAT0/status)

[ "$CHARGING" = "Charging" ] && exit;
[ "$PERCENT" -le 15 ] && notify-send "BRRrrr" "Bat low, bat low!"
